[hosts.guillermo]
network = "aws"
ip_addr = "3.84.125.53"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGLmvrICoTIZK7+QOd/AjeXly88pnxV2hUpZB4VhNldf"

[hosts.che]
network = "aws"
ip_addr = "34.201.149.94"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICrYPKXYxoMBt+k2wa258Hloa/9XusbznsUspc13y+cz"