[hosts.tomlette]
network = "mobile"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJK4vQXbVjrtKGffWk6kRlBT3FUmpEin+Aot7vF6lLRm"

[hosts.guillermo]
network = "aws"
ip_addr = "34.229.20.70"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILtH3Cw6EWNobPDEgf5OZX8Dpcn3L7YcCY+Ia4APet6v"
